### ISSUE TITLE
Enabled KernBypass apps get stuck on splash screen

### ISSUE THREAD

**Issue by Charcadet** [akusio/KernBypass-Public#1]
Apps enabled in KernBypass seem to get stuck on the loadscreen (splash screen) and then crash after a while.
iPhone 8+, 13.2.2, using checkra1n jailbreak.
Tested on: Nintendo Switch Online, Animal Crossing: Pocket Camp & various apps that don't need jb bypass. Same issue for all. 

Cr4shed did report a changerootfs crash when doing the stuff in terminal. Not sure if normal or not but here is some info from that:
Exception type: EXC_BAD_ACCES (SIGSEGV)
Exception subtype: KERN_INVALID_ADDRESS: 0x40
VM Protection: 0x40 is not in any region.

If I can be helpful in any way feel free to message me.

**Comment by hosam56** [comment]
I have the same issues.. checkra1n 13.3 iphone7

**Comment by vladkorotnev** [comment]
Just to make sure, didn't you forget to follow the instructions in the readme file to launch the support daemon?
I've not tested it myself but from reading the source it supposedly posts a kernel notification for the daemon to pick up, then stops the app. If the daemon isn't there, there's nobody to resume the app back.

@akusio I think it would be better to add the daemon into LaunchDaemons and start automatically with launchd maybe?

**Comment by Charcadet** [comment]
Found the fix for me.
Go to /var/MobileSoftwareUpdate/ in Filza and create a new folder called mnt1
Re-do your terminal commands and all should work fine.

Source: https://twitter.com/akusio_RR/status/1256901247799447552?s=20

**Comment by ghost** [comment]
The folder already exists for me, but Mario Kart and Mario Run still freeze and then crash after a while on my iPhone XR running iOS 13.3 and unc0ver 4.3.1.

![image](https://user-images.githubusercontent.com/482367/81194222-ae5a5280-8fbc-11ea-8b07-57b76d81d932.png)

Crash log: https://privatebin.at/?334366c869d1fe7b#6XRFv342CuQCJDHBRZadfncwHSYJk2fghc9PK5YfwK7T
