### ISSUE TITLE
Not working with newest Pokémon Go update

### ISSUE THREAD

**Issue by 3lack5ky** [akusio/KernBypass-Public#20]
Pokémon Go Version 1.141.2 is crashing instant on app launch. With version 1.141.1 it was working perfectly.

**Comment by cptmedic** [comment]
It still works on latest version
![image](https://user-images.githubusercontent.com/27046411/82778404-f2e84980-9e16-11ea-927a-8af4a1d67e49.jpeg)

**Comment by 3lack5ky** [comment]
Have you installed anything besides kernbypass? I tried reinstall the app and reconfigure kernbypass with terminal. For switch online app it works as normal, newest Pokémon Go crashes. If I downgrade Pokémon Go it is working again.

**Comment by cptmedic** [comment]
I will readily admit, I do not have that many tweaks installed minus things that improve UI appearance, so I am not sure. It very well could be a tweak trying to touch pokemon go on your end. The variables with the way this bypass work seem to be vastly different per user.

**Comment by 3lack5ky** [comment]
Ok, thank you :)
I will close this issue.

**Comment by endercypher** [comment]
@3lack5ky what tweaks do you have installed? Just curious.

**Comment by 3lack5ky** [comment]
I just exported the list via Flame, sorry for the long list 😅
PS: I saw a post on reddit about the new Pokémon update and many people who got their phones jailbroken in the past (but now got no jailbreak) seem to have the problem with crashing too. Only by restore without backup they solved it.


7-zip (POSIX): 16.02-1
Accent: 1.4.0
AlarmGroups: 2.0.3
AppList: 1.5.16
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Barmoji: 2020.3.1
Base Structure: 1-5
BatteryNotch: 1.5.7
BatteryPercentX [Public]: 1.4.1-33
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CattleGrid: 1.0.2
Cephei: 1.15
Cercube for YouTube: 5.1.18
ChargeAnimations: 3.0.6
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
CPDD Connect: 4.1.2
csdbgd: 2.1.0-248
Cydia Installer: 1.1.33
Cydia Substrate: 0.9.7101
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DolphiniOS: 2.2.3-4
FDots: 1.0.1
file: 5.35-2
Filza File Manager: 3.7.5-9
Find Utilities: 4.6.0-2
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
Graphite Library: 1.1.2
grep: 3.1-1
gzip: 1.9-1
HideBarX [Public]: 0.0.4
HomePlus Beta: 0.4.9-beta
iOS Firmware: 13.4.1
iPhone Firmware (/sbin): 0-1
KernBypass: 0.0.2
KillBackground13: 1.0.3
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libcolorpicker: 1.6.7
libCSColorPicker: 1.0
libidn2: 6.1.2-1
libplist: 2.0.0-2
libskittycolor: 1.0
libSparkAppList: 1.0.9
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+g5420cb5-1
Locale Profiles in UTF-8: 1.0-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NewTerm (iOS 10 – 13): 2.4
Notchification: 2.1-1
OhMyFlash: 1.0.0
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4
Profile Directory: 0-1
readline: 8.0-1
RealCC: 1.0.2
Rocket for Instagram: 3.6.16
RocketBootstrap: 1.0.9
Safari Plus: 1.7.12
sed: 4.5-1
shell-cmds: 118-8
Snappy: 1.3.0
Substrate Safe Mode: 0.9.6003
Sunflower: 1.1
system-cmds: 790.30.1-2
Tap Tap Lock: 1.1
Tape Archive: 1.30-2
TapTapFlip: 1.5
TweakRestrictor: 1.0.2
UIKit Tools: 1.1.17-1
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
VRBypass: 0.0.1
WallpaperLoader: 1.0
Waqt: 1.0.3
Watusi 2 for WhatsApp: 1.2.40
WatusiTools: 2.1.22
wget: 1.19.5-2
WGradRemover: 1.0-3
WiFi Passwords: 3.0.1
XZ Utils: 5.2.4-4
zip: 2.32-1

**Comment by endercypher** [comment]
So I’ve found that there’s something left over in /var/ after a rootfs restore that Pokémon Go now checks for. Upon rootfs & now a mobile obliteration aka using settings & erasing all data. I was able to now use Pokémon Go and I also restored my backup.
