### ISSUE TITLE
changerootfs seg faults on iOS 13.5 unc0ver

### ISSUE THREAD

**Issue by Not-Nik** [akusio/KernBypass-Public#30]
As said in the title I'm on an iPhone 8 Plus with iOS 13.5, jailbroken using unc0ver version 5.0.1. I'm getting the following output when following steps 1 and 2 from the readme:
![IMG_4240](https://user-images.githubusercontent.com/32980656/83636049-a2c47080-a5e8-11ea-919a-d8fe9d3d150d.jpg)

**Comment by Qrivi** [comment]
You should be able to get rid of this issue by creating the `/var/MobileSoftwareUpdate/mnt1` folder yourself, then run `changerootfs &` again.

**Comment by Not-Nik** [comment]
Works now thanks
