### ISSUE TITLE
Running changerootfs & hangs

### ISSUE THREAD

**Issue by dallasgroot** [akusio/KernBypass-Public#9]
Hey there, I’m on iOS 13.3.1 iPhone X, running `changerootfs & ` just hangs (see screenshot). 
![63AA4632-3C92-4FEB-B03B-F374223E953A](https://user-images.githubusercontent.com/7484579/80995164-aea6f200-8df2-11ea-8016-845f5d4f029f.png)

C4shed also detects changrootfs right when the command is executed.

**Comment by dallasgroot** [comment]
Pressing enter on the keyboard brings up the segmented fault.

**Comment by 6unsatiable** [comment]
does same for me, how long do i need to wait?

**Comment by 6unsatiable** [comment]
i just had a thought. we both are running 13.3.1 checkrain, maybe that could be the issue 🤔

**Comment by Randomblock1** [comment]
If you get a segfault, make sure /var/MobileSoftwareUpdate/mnt1 exists

**Comment by dallasgroot** [comment]
created the folder as it didn't exist, but i'm still getting the segmentation fault. I also rebooted and re ran with no success.

**Comment by dallasgroot** [comment]
Update, just updated my iPhone to 13.4.1 and re ran changerootfs & with no issues. So it might be an iOS 13.3.1 issue then.
